export default {
  "ice_creams": {
    "41f8da79-6f07-43be-b7ed-d3d3204c7a13": {
        "name": "Caramel Chocolate Cheesecake",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/caramel-chocolate-cheesecake-truffles-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/caramel-chocolate-cheesecake-truffles-landing-open.png",
        "description": "Caramel Cheesecake Ice Cream with Graham Cracker-Covered Cheesecake Truffles & Chocolate Cookie Swirls",
        "story": "In your cheesecake dreams, is it like you’re spooning through a world of caramel cheesecake ice cream swirled with chocolate cookies in a wonderland of truffles filled with cheesecake? Hello? You can wake up now…",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "water",
            "liquid sugar (sugar",
            "water)",
            "sugar",
            "corn syrup",
            "canola oil",
            "cream cheese (pasteurized milk",
            "cream",
            "cheese cultures",
            "salt",
            "carob bean gum)",
            "coconut oil",
            "egg yolks",
            "wheat flour",
            "dried cane syrup",
            "soybean oil",
            "graham flour",
            "eggs",
            "cocoa (processed with alkali)",
            "natural flavors",
            "cocoa",
            "guar gum",
            "butteroil",
            "milk protein concentrate",
            "corn starch",
            "salt",
            "soy lecithin",
            "tapioca starch",
            "pectin",
            "caramelized sugar syrup",
            "baking soda",
            "molasses",
            "honey",
            "carrageenan",
            "vanilla extract"
        ],
        "allergy_info": "contains milk, eggs, wheat and soy",
        "dietary_certifications": "Kosher",
        "productId": "2190",
        "id": "41f8da79-6f07-43be-b7ed-d3d3204c7a13"
    },
    "2b56b963-e4e5-4af4-83f5-d44c06f63733": {
        "name": "Chillin' the Roast™",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chillin-the-roast-truffles-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chillin-the-roast-truffles-landing-open.png",
        "description": "Cold Brew Coffee Ice Cream with Chocolate Cookie-Covered Coffee Liqueur Truffles & Fudge Swirls",
        "story": "Our cold brew coffee ice cream not only delivers a chillacious blast of creamy caffeination, it’s also loaded with enough coffee liqueur-filled, cookie crumble-covered truffles to fuel a truffolution.",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "liquid sugar (sugar",
            "water)",
            "water",
            "sugar",
            "coconut oil",
            "egg yolks",
            "butter (cream",
            "salt)",
            "coffee",
            "wheat flour",
            "milk protein concentrate",
            "cocoa (processed with alkali)",
            "soybean oil",
            "guar gum",
            "natural flavor",
            "salt",
            "corn starch",
            "canola oil",
            "rum",
            "soy lecithin",
            "chocolate",
            "baking soda",
            "carrageenan"
        ],
        "allergy_info": "contains milk, eggs, wheat and soy",
        "dietary_certifications": "Kosher",
        "productId": "2189",
        "id": "2b56b963-e4e5-4af4-83f5-d44c06f63733"
    },
    "e68e1318-1df9-46d7-a4b5-d1de3269fbb0": {
        "name": "Chocolate Shake It™",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chocolate-shake-it-truffles-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chocolate-shake-it-truffles-landing-open.png",
        "description": "Chocolate Malt Milkshake Ice Cream with Chocolate Cookie-Covered Fudge Truffles & Marshmallow Swirls",
        "story": "For those who prefer their ice cream shaken, swirled, and truffled, here’s a chocolate malt milkshake and marshmallow creation we truffled up with euphoric morsels of cookie crumble-covered fudge.",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "liquid sugar (sugar",
            "water)",
            "water",
            "corn syrup",
            "sugar",
            "coconut oil",
            "egg yolks",
            "cocoa (processed with alkali)",
            "corn starch",
            "wheat flour",
            "barley malt",
            "vanilla extract",
            "soybean oil",
            "eggs",
            "egg whites",
            "milk",
            "guar gum",
            "salt",
            "natural flavors",
            "soy lecithin",
            "canola oil",
            "pectin",
            "baking soda",
            "enzymes",
            "carrageenan"
        ],
        "allergy_info": "contains milk, eggs, wheat and soy",
        "dietary_certifications": "Kosher",
        "productId": "2188",
        "id": "e68e1318-1df9-46d7-a4b5-d1de3269fbb0"
    },
    "b9c21b76-330a-45e6-9158-519c441f7963": {
        "name": "One Sweet World",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/one-sweet-world-landing-closed.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/one-sweet-world-landing-open.png",
        "description": "Coffee Caramel Ice Creams with Fudge Chunks & Swirls of Marshmallow & Salted Caramel",
        "story": "At Ben & Jerry’s, we believe the world is sweetest when we stand together as one. That’s why we’re asking you to join us in digging deeper to understand issues of racial justice in America. Learn more and take action at benjerry.com/digdeeper",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "corn syrup",
            "water",
            "liquid sugar (sugar",
            "water)",
            "sugar",
            "coconut oil",
            "coffee extract",
            "egg yolks",
            "cocoa (processed with alkali)",
            "butter (cream",
            "salt)",
            "egg whites",
            "caramelized sugar syrup",
            "cocoa",
            "sea salt",
            "natural flavor",
            "pectin",
            "carrageenan",
            "guar gum",
            "baking soda",
            "soy lecithin",
            "vanilla extract",
            "salt",
            "milk"
        ],
        "allergy_info": "",
        "dietary_certifications": "Kosher",
        "productId": "2139",
        "id": "b9c21b76-330a-45e6-9158-519c441f7963"
    },
    "a5ffbe1a-7ada-40cc-a2af-63a6e13a3e97": {
        "name": "Americone Dream®",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/americone-dream-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/americone-dream-landing-open.png",
        "description": "Vanilla Ice Cream with Fudge-Covered Waffle Cone Pieces & a Caramel Swirl",
        "story": "Founded in fudge-covered waffle cones, this caramel-swirled concoction is the only flavor that gets a s'cream of approval from The Late Show host, Stephen Colbert. What's sweeter is this flavor supports charitable causes through The Stephen Colbert AmeriCone Dream Fund.",
        "sourcing_values": [],
        "ingredients": [
            ""
        ],
        "allergy_info": "",
        "dietary_certifications": "",
        "productId": "641",
        "id": "a5ffbe1a-7ada-40cc-a2af-63a6e13a3e97"
    },
    "f22b364c-11c6-4ddb-bcdc-12ba9cbde488": {
        "name": "Banana Split",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/banana-split-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/banana-split-landing-open.png",
        "description": "Banana & Strawberry Ice Creams with Walnuts, Fudge Chunks & a Fudge Swirl",
        "story": "We turned the classic ice cream parlor sundae you've always loved into the at-home flavor creation you've always wanted. Enjoy!",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "water",
            "liquid sugar (sugar",
            "water)",
            "sugar",
            "strawberries",
            "strawberry puree",
            "walnuts",
            "egg yolks",
            "bananas",
            "butter (cream",
            "salt)",
            "coconut oil",
            "cocoa processed with alkali",
            "chocolate liquor",
            "cocoa powder",
            "lemon juice concentrate",
            "natural flavors",
            "guar gum",
            "pectin",
            "milkfat",
            "carrageenan",
            "soy lecithin",
            "vanilla extract"
        ],
        "allergy_info": "may contain other tree nuts",
        "dietary_certifications": "Kosher",
        "productId": "602",
        "id": "f22b364c-11c6-4ddb-bcdc-12ba9cbde488"
    },
    "7657ed76-e206-4bb6-965d-625ff8107a26": {
        "name": "Blondie Ambition™",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/blondie-ambition-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/blondie-ambition-landing-open.png",
        "description": "Buttery Brown Sugar Ice Cream with Blonde Brownies and Butterscotch Toffee Flakes",
        "story": "What makes Ben & Jerry's so euphoric? Some say it's the legendary creamy-richness of our flavor creations. Others say it's the tastebud-boggling combinations of spoon-bending chunks & perfect swirls. We say, \"Enjoy!\"",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "water",
            "liquid sugar (sugar",
            "water)",
            "brown sugar",
            "egg yolks",
            "dried cane syrup",
            "wheat flour",
            "eggs",
            "coconut oil",
            "sugar",
            "butter (cream",
            "salt)",
            "milkfat",
            "soybean oil",
            "corn syrup",
            "salt",
            "guar gum",
            "vanilla extract",
            "corn starch",
            "monocalcium phosphate",
            "sodium acid pyrophosphate",
            "sodium bicarbonate",
            "cocoa",
            "molasses",
            "natural flavor",
            "paprika extract (color)",
            "soy lecithin",
            "carrageenan",
            "lemon juice concentrate"
        ],
        "allergy_info": "",
        "dietary_certifications": "",
        "productId": "1381",
        "id": "7657ed76-e206-4bb6-965d-625ff8107a26"
    },
    "562d61e1-d48b-493d-b975-b1e3abf59e85": {
        "name": "Boom Chocolatta™ Cookie Core",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/boom-chocolatta-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/boom-chocolatta-landing.png",
        "description": "Mocha & Caramel Ice Creams with Chocolate Cookies, Fudge Flakes & a Chocolate Cookie Core",
        "story": "As you slam dunk your spoon through creamy mocha & caramel to celebrate the epic chocolate cookie-spread core, your technique may not be perfect, but the victory’s perfectly delicious.",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "liquid sugar (sugar",
            "water)",
            "water",
            "sugar",
            "soybean oil",
            "cocoa (processed with alkali)",
            "egg yolks",
            "butter (cream",
            "salt)",
            "coffee extract",
            "corn syrup",
            "rice flour",
            "potato flour",
            "wheat flour",
            "coconut oil",
            "brown sugar",
            "vanilla extract",
            "salt",
            "sodium bicarbonate",
            "natural flavor",
            "cocoa powder",
            "soy lecithin",
            "eggs",
            "chocolate liquor",
            "cocoa butter",
            "milk",
            "whey protein concentrate",
            "guar gum",
            "carrageenan",
            "milkfat"
        ],
        "allergy_info": "",
        "dietary_certifications": "",
        "productId": "1271",
        "id": "562d61e1-d48b-493d-b975-b1e3abf59e85"
    },
    "1c0d0e69-d05e-44b5-8e70-045866a8419e": {
        "name": "Bourbon Pecan Pie",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/bourbonpeacanpie-pint-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/bourbonpeacanpie-pint-landing-open.png",
        "description": "Buttery Bourbon Ice Cream with Pecans, Shortbread Cookie Pieces & a Whiskey Caramel Swirl",
        "story": "Not long ago we scoop-toured through Texas asking you to elect the best of two Texas-inspired flavors. Thanks to you this bourbon-y whirl of pecans and cookies wrapped in whiskey-kissed caramel is now available Tex-clusively!",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "liquid sugar (sugar",
            "water)",
            "water",
            "corn syrup",
            "pecans",
            "butter (cream",
            "salt)",
            "wheat flour",
            "egg yolks",
            "sugar",
            "dried cane syrup",
            "whiskey",
            "dry malt extract (barley)",
            "soybean oil",
            "salt",
            "eggs",
            "caramel color",
            "peanut oil",
            "guar gum",
            "baking soda",
            "carrageenan",
            "soy lecithin may contain other tree nuts"
        ],
        "allergy_info": "may contain other tree nuts",
        "dietary_certifications": "Kosher",
        "productId": "1490",
        "id": "1c0d0e69-d05e-44b5-8e70-045866a8419e"
    },
    "1793aec5-1614-4e73-9213-c1b31ec50da1": {
        "name": "Brewed to Matter™",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/brewed-to-matter-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/brewed-to-matter-landing-open.png",
        "description": "Coffee Ice Cream with Fudge Chunks & a Brownie Batter Swirl",
        "story": "We're thrilled to add this made-to-matter, brownie batter-swirled batchful of coffee awesomeness to the Ben & Jerry's family of flavors. It packs a powerful pintful of goodness that's guaranteed to amaze you with every consciously concocted bite.",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "ingredients: cream",
            "skim milk",
            "liquid sugar (sugar",
            "water)",
            "water",
            "sugar",
            "coffee extract",
            "coconut oil",
            "egg yolks",
            "dried cane syrup",
            "cocoa (processed with alkali)",
            "cocoa",
            "butter (cream",
            "salt)",
            "corn syrup",
            "wheat flour",
            "chocolate liquor",
            "canola oil",
            "carrageenan",
            "guar gum",
            "salt",
            "soy lecithin",
            "natural flavor",
            "vanilla extract",
            "milk fat",
            "sodium bicarbonate"
        ],
        "allergy_info": "",
        "dietary_certifications": "",
        "productId": "1379",
        "id": "1793aec5-1614-4e73-9213-c1b31ec50da1"
    },
    "b7513038-8234-4d64-a3e4-a9fee9d9c1ee": {
        "name": "Brownie Batter Core",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/brownie-batter-core-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/brownie-batter-core-landing.png",
        "description": "Chocolate & Vanilla Ice Creams with Fudge Brownies & a Brownie Batter Core",
        "story": "Spooning your way to brownie nirvana? Smack dab in the middle of this brownie-chunk-filled ice cream there's a core of unbaked brownie batter calling your name. No, really. We heard it.",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Greyston Brownies",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "liquid sugar (sugar",
            "water)",
            "skim milk",
            "water",
            "dried cane syrup",
            "sugar",
            "cocoa (pressed with alkali)",
            "egg yolks",
            "wheat flour",
            "butter (cream",
            "salt)",
            "corn syrup",
            "cocoa",
            "cocoa powder",
            "chocolate liquor",
            "soybean oil",
            "invert sugar",
            "coconut oil",
            "vanilla extract",
            "eggs",
            "canola oil",
            "salt",
            "carrageenan",
            "guar gum",
            "egg whites",
            "natural flavor",
            "soy lecithin",
            "baking soda",
            "malted barley flour"
        ],
        "allergy_info": "",
        "dietary_certifications": "Kosher",
        "productId": "1515",
        "id": "b7513038-8234-4d64-a3e4-a9fee9d9c1ee"
    },
    "63200cb5-d6e9-4510-b27d-f5f2c6a65518": {
        "name": "Cheesecake Brownie",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/cheesecake-brownie-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/cheesecake-brownie-landing-open.png",
        "description": "Cheesecake Ice Cream with Cheesecake Brownie Chunks",
        "story": "What do you call a creamy cheesecake ice cream filled with dreamy cheesecake brownies? A surreally good reason to go fetch a spoon. Enjoy!",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Greyston Brownies",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "water",
            "liquid sugar (sugar",
            "water)",
            "dried cane syrup",
            "corn syrup",
            "cream cheese (pasteurized milk",
            "cream",
            "cheese cultures",
            "salt",
            "carob bean gum)",
            "soybean oil",
            "wheat flour",
            "egg yolks",
            "eggs",
            "cocoa",
            "corn starch",
            "salt",
            "sugar",
            "guar gum",
            "natural flavor",
            "pectin",
            "soy lecithin",
            "vanilla extract",
            "xanthan gum",
            "carrageenan"
        ],
        "allergy_info": "",
        "dietary_certifications": "Kosher",
        "productId": "607",
        "id": "63200cb5-d6e9-4510-b27d-f5f2c6a65518"
    },
    "9b541d8b-4346-4fdf-86f0-5f55187a5dd1": {
        "name": "Cherry Garcia®",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/cherry-garcia-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/cherry-garcia-landing-open.png",
        "description": "Cherry Ice Cream with Cherries & Fudge Flakes",
        "story": "Our euphorically edible tribute to guitarist Jerry Garcia & Grateful Dead fans everywhere, it’s the first ice cream named for a rock legend and the most famous of our fan-suggested flavors.",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "liquid sugar (sugar",
            "water)",
            "water",
            "cherries",
            "sugar",
            "egg yolks",
            "coconut oil",
            "cocoa (processed with alkali)",
            "fruit and vegetable concentrates (color)",
            "cocoa powder",
            "guar gum",
            "natural flavors",
            "lemon juice concentrate",
            "carrageenan",
            "milk fat",
            "soy lecithin"
        ],
        "allergy_info": "",
        "dietary_certifications": "Kosher",
        "productId": "608",
        "id": "9b541d8b-4346-4fdf-86f0-5f55187a5dd1"
    },
    "47956977-f14c-4d8f-8db4-1bd57fbbbcdb": {
        "name": "Chocolate Chip Cookie Dough",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/choc-chip-cookie-dough-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/choc-chip-cookie-dough-landing-open.png",
        "description": "Vanilla Ice Cream with Gobs of Chocolate Chip Cookie Dough",
        "story": "We knew we were onto something big when we made the world’s first batch of Chocolate Chip Cookie Dough ice cream in 1984. Today the flavor still reigns among our all-time most popular concoctions.",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "liquid sugar (sugar",
            "water)",
            "water",
            "wheat flour",
            "sugar",
            "brown sugar",
            "egg yolks",
            "butter (cream",
            "salt)",
            "expeller pressed soybean oil",
            "eggs",
            "coconut oil",
            "chocolate liquor",
            "vanilla extract",
            "cocoa (processed with alkali)",
            "cocoa powder",
            "salt",
            "molasses",
            "guar gum",
            "cocoa butter",
            "natural flavors",
            "carrageenan",
            "milkfat",
            "soy lecithin"
        ],
        "allergy_info": "",
        "dietary_certifications": "Kosher",
        "productId": "610",
        "id": "47956977-f14c-4d8f-8db4-1bd57fbbbcdb"
    },
    "03779559-5ab9-4fcf-b440-a73e69ab4791": {
        "name": "Chocolate Fudge Brownie",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chocolate-fudge-brownie-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chocolate-fudge-brownie-landing-open.png",
        "description": "Chocolate Ice Cream with Fudge Brownies",
        "story": "The fabulously fudgy brownies in this flavor come from New York’s Greyston Bakery, where producing great baked goods is part of their greater-good mission to provide jobs and training to low-income city residents.",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Greyston Brownies",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "liquid sugar (sugar",
            "water)",
            "skim milk",
            "water",
            "sugar",
            "cocoa (processed with alkali)",
            "wheat flour",
            "cocoa powder",
            "soybean oil",
            "egg yolks",
            "invert cane sugar",
            "eggs",
            "egg whites",
            "guar gum",
            "salt",
            "carrageenan",
            "vanilla extract",
            "malted barley flour",
            "sodium bicarbonate"
        ],
        "allergy_info": "",
        "dietary_certifications": "Kosher",
        "productId": "611",
        "id": "03779559-5ab9-4fcf-b440-a73e69ab4791"
    },
    "58ebfd39-bb2b-4e5f-ae80-4d060c62885a": {
        "name": "Chocolate Therapy®",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chocolate-therapy-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chocolate-therapy-landing-open.png",
        "description": "Chocolate Ice Cream with Chocolate Cookies & Swirls of Chocolate Pudding Ice Cream",
        "story": "You know how sometimes you just want to scream? You could just scream, or you could grab a spoon, get a grip, and treat yourself to some primal s'cream therapy of the sublimest chocolate kind. (Euphoria may occur upon tasting.)",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "liquid sugar (sugar",
            "water)",
            "skim milk",
            "water",
            "cocoa (processed with alkali)",
            "wheat flour",
            "sugar",
            "soybean oil",
            "egg yolks",
            "chocolate liquor",
            "brown sugar",
            "cocoa",
            "honey",
            "guar gum",
            "vanilla extract",
            "natural flavors",
            "salt",
            "sodium bicarbonate",
            "cocoa butter",
            "carrageenan",
            "soy lecithin"
        ],
        "allergy_info": "",
        "dietary_certifications": "Kosher",
        "productId": "614",
        "id": "58ebfd39-bb2b-4e5f-ae80-4d060c62885a"
    },
    "e4f8bab0-6382-47bb-a32c-faa1baab5b09": {
        "name": "Chubby Hubby®",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chubby-hubby-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chubby-hubby-landing-open.png",
        "description": "Vanilla Malt Ice Cream with Peanutty Fudge-Covered Pretzels with Fudge & Peanut Buttery Swirls",
        "story": "Two tricksters convinced a co-worker this flavor really existed (it didn’t), then felt guilty and made him an actual batch packed with pretzels, peanut butter & fudge. He loved it, so did we, and the rest is history. Enjoy!",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "liquid sugar (sugar",
            "water)",
            "water",
            "sugar",
            "peanuts",
            "pretzels (wheat flour",
            "soybean oil",
            "salt",
            "malt)",
            "partially defatted peanut flour",
            "egg yolks",
            "coconut oil",
            "palm kernel oil",
            "wheat flour and malt barley extract",
            "peanut oil",
            "butter (cream",
            "salt)",
            "cocoa (processed with alkali)",
            "vanilla extract",
            "milk",
            "salt",
            "chocolate liquor",
            "guar gum",
            "cocoa",
            "natural flavors",
            "soy lecithin",
            "sodium bicarbonate",
            "carrageenan"
        ],
        "allergy_info": "may contain tree nuts",
        "dietary_certifications": "Kosher",
        "productId": "615",
        "id": "e4f8bab0-6382-47bb-a32c-faa1baab5b09"
    },
    "a9398630-f017-4578-81ae-803f6bbe47f0": {
        "name": "Chunky Monkey®",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chunky-monkey-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/chunky-monkey-landing-open.png",
        "description": "Banana Ice Cream with Fudge Chunks & Walnuts",
        "story": "To create a flavor as fun as the name, we monkeyed around with bunches of test batches until we knew we had a winner: the nuttiest chocolatey-chunkiest concoction-gone-bananas you'll ever go ape for.",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "liquid sugar (sugar",
            "water)",
            "water",
            "sugar",
            "bananas",
            "walnuts",
            "coconut oil",
            "egg yolks",
            "cocoa (processed with alkali)",
            "cocoa powder",
            "lemon juice concentrate",
            "guar gum",
            "natural flavors",
            "milkfat",
            "carrageenan",
            "soy lecithin",
            "vanilla extract"
        ],
        "allergy_info": "may contain other tree nuts",
        "dietary_certifications": "Kosher",
        "productId": "616",
        "id": "a9398630-f017-4578-81ae-803f6bbe47f0"
    },
    "b0a7ae00-b2d8-402e-8b7c-ea0aff0c9f16": {
        "name": "Cinnamon Buns®",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/cinnamon-bun-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/cinnamon-bun-landing-open.png",
        "description": "Caramel Ice Cream with Cinnamon Bun Dough & a Cinnamon Streusel Swirl",
        "story": "Our cool salute to cinnamon buns is so cinnamon-streuseled & dough-loaded, there's no telling where the cinnamon buns end or the ice cream begins. That's because it's one fun flavor all the way through. Enjoy!",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "water",
            "liquid sugar (sugar",
            "water)",
            "sugar",
            "dried cane syrup",
            "wheat flour",
            "corn syrup",
            "egg yolks",
            "brown sugar",
            "soybean oil",
            "butter (cream",
            "salt)",
            "coconut oil",
            "molasses",
            "salt",
            "cinnamon",
            "soy lecithin",
            "sodium bicarbonate",
            "spice",
            "vanilla extract",
            "guar gum",
            "carrageenan"
        ],
        "allergy_info": "",
        "dietary_certifications": "Kosher",
        "productId": "617",
        "id": "b0a7ae00-b2d8-402e-8b7c-ea0aff0c9f16"
    },
    "3e405964-2c9d-4f4d-bf62-fec21e3053dd": {
        "name": "Coconuts for Caramel Core",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/coconuts-for-caramel-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/coconuts-for-caramel-landing.png",
        "description": "Caramel & Sweet Cream Coconut Ice Creams with Fudge Flakes & a Caramel Core",
        "story": "How do you spoon your way to euphoria? Do you start with a cool cruise through fudge-kissed coconutty ocean, a quick dip in the caramel sea, or a thrill-dive deep in the well of thick, gooey caramel? Well?",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "water",
            "liquid sugar (sugar",
            "water)",
            "coconut",
            "sugar",
            "milk",
            "corn syrup",
            "egg yolks",
            "coconut oil",
            "corn starch",
            "cocoa (processed with alkali)",
            "butter (cream",
            "salt)",
            "milk fat",
            "cocoa powder",
            "pectin",
            "caramelized sugar syrup",
            "guar gum",
            "baking soda",
            "lactase",
            "soy lecithin",
            "vanilla extract",
            "salt",
            "carrageenan",
            "natural flavor"
        ],
        "allergy_info": "",
        "dietary_certifications": "Kosher",
        "productId": "1514",
        "id": "3e405964-2c9d-4f4d-bf62-fec21e3053dd"
    },
    "9383cd96-c0a4-42d5-8e31-bd8a17f34369": {
        "name": "Coffee Toffee Bar Crunch",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/coffee-toffee-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/coffee-toffee-landing-open.png",
        "description": "Coffee Ice Cream with Fudge-Covered Toffee Pieces",
        "story": "Coffee What Bar Crunch? We gave this flavor a new name to go with the new toffee bars we’re using as part of our commitment to source Fairtrade Certified and non-GMO ingredients. We love it and know you will too!",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "liquid sugar (sugar",
            "water)",
            "water",
            "sugar",
            "coconut oil",
            "coffee extract",
            "egg yolks",
            "butter (cream",
            "salt)",
            "almonds",
            "cocoa (processed with alkali)",
            "milk",
            "soy lecithin",
            "cocoa",
            "natural flavor",
            "salt",
            "vanilla extract",
            "vegetable oil (canola",
            "safflower",
            "and/or sunflower oil)",
            "guar gum",
            "carrageenan"
        ],
        "allergy_info": "may contain wheat, peanuts and other tree nuts",
        "dietary_certifications": "Kosher",
        "productId": "618",
        "id": "9383cd96-c0a4-42d5-8e31-bd8a17f34369"
    },
    "be70b2d9-8b26-4c06-9b5c-937529a1fb2f": {
        "name": "Coffee, Coffee BuzzBuzzBuzz!®",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/coffee-coffee-buzz-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/coffee-coffee-buzz-landing-open.png",
        "description": "Coffee Ice Cream with Espresso Bean Fudge Chunks",
        "story": "Somewhere between the creamy coffee coffee ice cream and the buzzbuzzbuzz of espresso fudge, it hits you: you’re wide awake and in lovelovelove.",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "skim milk",
            "liquid sugar (sugar",
            "water)",
            "water",
            "sugar",
            "coconut oil",
            "coffee extract",
            "cocoa (processed with alkali)",
            "egg yolks",
            "coffee",
            "guar gum",
            "soy lecithin",
            "vanilla extract",
            "natural flavor",
            "carrageenan"
        ],
        "allergy_info": "",
        "dietary_certifications": "Kosher",
        "productId": "1003",
        "id": "be70b2d9-8b26-4c06-9b5c-937529a1fb2f"
    },
    "1b05c2e4-ac6e-45e0-ad71-11644df067f9": {
        "name": "Cookies & Cream Cheesecake Core",
        "image_closed": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/cookies-and-cream-cheesecake-landing.png",
        "image_open": "/files/live/sites/systemsite/files/flavors/products/us/pint/open-closed-pints/cookies-and-cream-cheesecake-landing.png",
        "description": "Chocolate & Cheesecake Ice Creams with Chocolate Cookies & a Cheesecake Core",
        "story": "What's it called when you find yourself spoon-deep in a rich center of cheesecake in the middle of a cool ice cream universe of chocolate, cheesecake & cookies? A Core encounter of the Ben & Jerriest kind.",
        "sourcing_values": [
            "Non-GMO",
            "Cage-Free Eggs",
            "Fairtrade",
            "Responsibly Sourced Packaging",
            "Caring Dairy"
        ],
        "ingredients": [
            "cream",
            "liquid sugar (sugar",
            "water)",
            "skim milk",
            "water",
            "sugar",
            "cocoa (processed with alkali)",
            "butter (cream",
            "salt)",
            "wheat flour",
            "egg yolks",
            "coconut oil",
            "cream cheese (pasteurized milk",
            "cream",
            "cultures",
            "salt",
            "locust bean gum)",
            "milk protein concentrate",
            "brown sugar",
            "modified corn starch",
            "soy lecithin",
            "eggs",
            "carrageenan",
            "salt",
            "natural flavor",
            "guar gum",
            "locust bean gum",
            "baking soda",
            "vanilla extract",
            "xantham gum"
        ],
        "allergy_info": "",
        "dietary_certifications": "Kosher",
        "productId": "1516",
        "id": "1b05c2e4-ac6e-45e0-ad71-11644df067f9"
    }
  }
}